dist: trusty
sudo: required
language: c
compiler:
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake libtool libgnutls28-dev libev-dev libwrap0-dev libpam0g-dev liblz4-dev libseccomp-dev libreadline-dev libnl-route-3-dev libkrb5-dev

script: autoreconf -fvi && ./configure && make && make check

