dist: trusty
sudo: required
language: c
compiler:
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libwrap0-dev libpam0g-dev liblz4-dev libseccomp-dev libreadline-dev
    libnl-route-3-dev libkrb5-dev liboath-dev libprotobuf-c0-dev libtalloc-dev
    libhttp-parser-dev libpcl1-dev libopts25-dev autogen protobuf-c-compiler gperf
    liblockfile-bin nuttcp lcov libtool automake autoconf gettext libgnutls-dev
    libev-dev

script: 
  autoreconf -fvi && ./configure --enable-code-coverage && make -j4 && make -j4 check && make code-coverage-capture

